# Generated by Django 5.0.6 on 2024-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=255, verbose_name='Описание блюда')),
                ('photo', models.ImageField(upload_to='popular_category/', verbose_name='Фото блюда')),
            ],
            options={
                'verbose_name': 'Популярная категория',
                'verbose_name_plural': 'Популярные категории',
            },
        ),
        migrations.AddField(
            model_name='base',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
