# Generated by Django 5.0.6 on 2024-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_our_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Фото')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('date_to', models.CharField(max_length=155, verbose_name='Дата создание 1')),
                ('date_form', models.CharField(max_length=155, verbose_name='Дата создание 2')),
                ('food1', models.CharField(max_length=155, verbose_name='Еда 1')),
                ('food2', models.CharField(max_length=155, verbose_name='Еда 2')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
